### ISSUE TITLE
[BUG] Issue with 'null' question and response `API Response`

### ISSUE THREAD

**Issue by Iheuzio** [Iheuzio/gpt-contextfiles#18]
**Describe the bug**
After clearing the context window, or opening vscode with the extension for the first time you'll see that clicking `API Response` will show null twice instead of not showing anything.

**To Reproduce**
1. Open vscode with extension loaded
2. Open the extension window
3. Click `API Response`

**Expected behavior**
Clicking `API Response` will not do anything if nothing is provided

**Screenshots**
![image](https://github.com/Iheuzio/gpt-contextfiles/assets/97270760/d28eb879-1d4d-4f99-b4e2-bed9ca3c7a6f)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - VSCode version: 1.80.0-insider

**Comment by KarthikShetty5** [comment]
in which file , those are there

**Comment by Ajaykrishna-RK** [comment]
can u assign me this?

**Comment by Iheuzio** [comment]
# File and code believed to be the issue

File: `extension.js`

![image](https://github.com/Iheuzio/gpt-contextfiles/assets/97270760/63b9f7dd-e72d-4ae0-881f-07f81735d587)


Within lines 441-453

# Description

The null is shown when using the ternary operator, instead of ignoring the operation. It prints null for the question and answer from the response.
